on:
  pull_request:

env:
  CI: true

# cancel in-progress runs on new commits to same PR (gitub.event.number)
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  lint_test_js:
    name: Lint & Test JS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        name: Setup pnpm

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: 20

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --silent --strict-peer-dependencies

      - name: Lint
        run: pnpm lint

      - name: Test
        run: pnpm test
